workspace/bk56_rip/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  root 'static_pages#home'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users

end

workspace/bk56_rip/app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
   has_secure_password
   validates :password, length: { minimum: 6 }
   validates :password_confirmation, presence: true
   validates :dob, presence: true
   validates :date, presence: true
   validates :repuation, presence: true
end

workspace/bk56_rip/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

workspace/bk56_rip/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def new
  end
   def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      flash[:success] = "Welcome to the language Q&A!"
      log_in @user
      redirect_to @user
    else
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end
 
  def destroy
    log_out
    redirect_to root_url
  end
  
   # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

workspace/bk56_rip/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

workspace/bk56_rip/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
     @user = User.find(params[:id])
       debugger
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:success] = "Welcome to the language Q&A!"
        redirect_to @user
      else
        render 'new'
      end
    
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :dob, :date, :repuation)
    end
end

workspace/bk56_rip/app/helpers/application_helper.rb
module ApplicationHelper
   # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

workspace/bk56_rip/app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
    current_user
  end
  
  def current_user
    
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

workspace/bk56_rip/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

workspace/bk56_rip/app/helpers/users_helper.rb
module UsersHelper
end

workspace/bk56_rip/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Rip Team
  </small>
</footer>

workspace/bk56_rip/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up",signup_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Sign In",login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

workspace/bk56_rip/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

workspace/bk56_rip/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

workspace/bk56_rip/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the language Q&A</h1>

  <h2>
    This is the home page of language Q&A
  </h2>

  <%= link_to "Sign up now!",signup_path, class: "btn btn-lg btn-primary" %>
</div>

workspace/bk56_rip/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.text_field :dob %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :repuation %><br>
    <%= f.number_field :repuation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

workspace/bk56_rip/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

workspace/bk56_rip/app/views/users/index.html.erb
<h1>Listing users</h1>
<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Dob</th>
      <th>Date</th>
      <th>Repuation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.dob %></td>
        <td><%= user.date %></td>
        <td><%= user.repuation %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

workspace/bk56_rip/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
     <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
    
    <%= f.label :dob %>
    <%= f.text_field :dob %>
    
    <%= f.label :date %>
    <%= f.text_field :date %>
    
    <%= f.label :repuation %>
    <%= f.text_field :repuation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

workspace/bk56_rip/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<!--<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>-->

<p>
  <strong>Dob:</strong>
  <%= @user.dob %>
</p>

<p>
  <strong>Date:</strong>
  <%= @user.date %>
</p>

<p>
  <strong>Repuation:</strong>
  <%= @user.repuation %>
</p>